sudo: false

language: go
go:
  - 1.7.3

services:
  - postgresql

addons:
  postgresql: "9.4"

before_install:
  - psql -c 'create database bosh;' -U postgres
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}/src/github.com/mattcui/bosh-softlayer-baremetal-server-release:$GOPATH"

script: bin/ci
branches:
  only:
  - master
  - develop
