sudo: required

language: go
go:
  - 1.7.3

services:
  - postgresql

addons:
  postgresql: "9.4"

before_install:
  - psql -c 'create database bosh;' -U postgres

script: bin/ci
branches:
  only:
  - master
  - develop
