sudo: required

language: go
go:
  - 1.7.3

services:
  - docker

before_install:
  - docker pull postgres:9.4.10
  - docker run -d -p 127.0.0.1:5432:5432 --name postgres -e POSTGRES_PASSWORD=postgres
  - docker ps -a
  - docker run -it --rm --link postgres:postgres postgres:9.4.10 sh -c "exec psql -h 127.0.0.1 -p 5432 -U postgres -c 'create database bosh'"

script: bin/ci
branches:
  only:
  - master
  - develop
